export const sampleData = [
    {
      item_name: "Moong Dal",
      code: "001",
      uom: "Kg",
      qty: 1,
      purchased_rate: 80,
      rate: 100,
      amount: 100,
    },
    {
      item_name: "Masoor Dal",
      code: "002",
      uom: "Kg",
      qty: 1,
      purchased_rate: 75,
      rate: 90,
      amount: 90,
    },
    {
      item_name: "Basmati Rice",
      code: "003",
      uom: "gram",
      qty: 1000,
      purchased_rate: 120,
      rate: 150,
      amount: 150,
    },
    {
      item_name: "Brown Rice",
      code: "004",
      uom: "gram",
      qty: 1000,
      purchased_rate: 100,
      rate: 130,
      amount: 130,
    },
    {
      item_name: "Wheat Flour",
      code: "005",
      uom: "Kg",
      qty: 1,
      purchased_rate: 40,
      rate: 50,
      amount: 50,
    },
    {
      item_name: "Refined Sugar",
      code: "006",
      uom: "gram",
      qty: 1000,
      purchased_rate: 45,
      rate: 55,
      amount: 55,
    },
    {
      item_name: "Brown Sugar",
      code: "007",
      uom: "gram",
      qty: 1000,
      purchased_rate: 50,
      rate: 60,
      amount: 60,
    },
    {
      item_name: "Salt",
      code: "008",
      uom: "Kg",
      qty: 1,
      purchased_rate: 10,
      rate: 12,
      amount: 12,
    },
    {
      item_name: "Full Cream Milk",
      code: "011",
      uom: "liter",
      qty: 1,
      purchased_rate: 55,
      rate: 65,
      amount: 65,
    },
    {
      item_name: "Skimmed Milk",
      code: "012",
      uom: "liter",
      qty: 1,
      purchased_rate: 50,
      rate: 60,
      amount: 60,
    },
    {
      item_name: "Butter",
      code: "013",
      uom: "piece",
      qty: 1,
      purchased_rate: 400,
      rate: 450,
      amount: 450,
    },
    {
      item_name: "Cheese",
      code: "014",
      uom: "piece",
      qty: 1,
      purchased_rate: 420,
      rate: 470,
      amount: 470,
    },
    {
      item_name: "Peanuts",
      code: "015",
      uom: "Kg",
      qty: 1,
      purchased_rate: 90,
      rate: 110,
      amount: 110,
    },
    {
      item_name: "Cashews",
      code: "016",
      uom: "Kg",
      qty: 1,
      purchased_rate: 700,
      rate: 850,
      amount: 850,
    },
    {
      item_name: "Cinnamon",
      code: "022",
      uom: "Kg",
      qty: 1,
      purchased_rate: 450,
      rate: 520,
      amount: 520,
    },
    {
      item_name: "Coriander Powder",
      code: "024",
      uom: "Kg",
      qty: 1,
      purchased_rate: 90,
      rate: 110,
      amount: 110,
    },
    {
      item_name: "Chili Powder",
      code: "026",
      uom: "Kg",
      qty: 1,
      purchased_rate: 120,
      rate: 140,
      amount: 140,
    },
    {
      item_name: "Coconut Oil",
      code: "043",
      uom: "liter",
      qty: 1,
      purchased_rate: 280,
      rate: 320,
      amount: 320,
    },
    {
      item_name: "Olive Oil",
      code: "044",
      uom: "liter",
      qty: 1,
      purchased_rate: 800,
      rate: 950,
      amount: 950,
    },
  ];
  